import type { Metadata } from "next";
export const metadata: Metadata = { title: "Leavigation | Terms and Conditions" };

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto max-w-3xl px-4 py-10">
        <header className="mb-8 flex items-baseline justify-between gap-4">
          <h1 className="text-2xl font-semibold text-slate-900">Terms and Conditions</h1>
          <a href="/plan" className="text-sm font-medium text-sky-600 hover:text-sky-700">← Back to planner</a>
        </header>
        <p className="text-xs text-slate-400 mb-8">Last updated: June 2026</p>
        <div className="space-y-6 text-sm leading-relaxed text-slate-800">

          <section>
            <h2 className="text-base font-semibold text-slate-900">1. Acceptance of Terms</h2>
            <p className="mt-2">By accessing or using Leavigation (leavigation.com), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the tool.</p>
            <p className="mt-2">We reserve the right to update these Terms at any time. Continued use of the tool after any update constitutes your acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">2. Description of Service</h2>
            <p className="mt-2">Leavigation is a free, self-service informational tool designed to help individuals understand how parental leave programs may apply to their situation. The tool generates personalized timelines and income estimates based on information you provide.</p>
            <p className="mt-2">Leavigation is not a licensed legal, financial, HR, or benefits advisory service. Use of this tool does not create any professional-client relationship.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">3. Eligibility</h2>
            <p className="mt-2">This tool is designed for use by employees in the United States only. You must be 18 years of age or older to use this service.</p>
            <p className="mt-2">By using this tool, you represent that you are using it for lawful purposes and in compliance with all applicable laws and regulations.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">4. Informational Purpose Only</h2>
            <p className="mt-2">All information provided by Leavigation is for general informational purposes only. It does not constitute legal, financial, employment, tax, or benefits advice.</p>
            <p className="mt-2">Leave entitlements, dollar estimates, and timelines shown are estimates only. Actual benefits depend on your specific eligibility, employer policies, claims history, and determinations made by your employer and/or state agency.</p>
            <p className="mt-2">Always verify current rules directly with your state&apos;s administering agency, your employer&apos;s HR department, and a qualified professional before making leave decisions.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">5. Accuracy of Information</h2>
            <p className="mt-2">We make every effort to keep the information on this site current and accurate. However, leave laws at the federal, state, and municipal level change frequently. Leavigation does not guarantee that all information is complete, accurate, or up to date at the time of your use.</p>
            <p className="mt-2">Links to official agency websites are provided where available to help you access the most current information.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">6. User Responsibilities</h2>
            <p className="mt-2">You are responsible for the accuracy and completeness of the information you provide to the tool. Estimates generated by Leavigation are only as accurate as the inputs you provide.</p>
            <p className="mt-2">You agree not to use this tool for any unlawful purpose or in any way that could damage, disable, or impair the service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">7. Intellectual Property</h2>
            <p className="mt-2">All content, design, and code on Leavigation is the property of Leavigation and its creators and is protected by applicable copyright and intellectual property laws.</p>
            <p className="mt-2">You may not reproduce, distribute, modify, or create derivative works from any content on this site without express written permission.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">8. Disclaimer of Warranties</h2>
            <p className="mt-2 uppercase text-xs leading-relaxed">LEAVIGATION IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. LEAVIGATION DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">9. Limitation of Liability</h2>
            <p className="mt-2 uppercase text-xs leading-relaxed">TO THE MAXIMUM EXTENT PERMITTED BY LAW, LEAVIGATION AND ITS CREATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SERVICE IS TO STOP USING IT.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">10. Governing Law</h2>
            <p className="mt-2">These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">11. Contact</h2>
            <p className="mt-2">If you have questions about these Terms, please contact us at <a href="mailto:leavigation@gmail.com" className="text-sky-600 hover:text-sky-700">leavigation@gmail.com</a>.</p>
          </section>

        </div>
      </div>
    </main>
  );
}
